#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if [ -e .commit ]
    then
        node scripts/matter.lint.js --staged --includes source/ -w -a
        rm -f .commit
        npm run analyse -- -w -a
        git commit --amend --no-edit --no-verify
fi
