#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if [ -e .commit ]
    then
        npm run matterlint -- --staged -a
        npm run analyse -- -w -a
        rm -f .commit
        git commit --amend --no-edit --no-verify
fi
