name: updating
on:
    repository_dispatch:
        types:
            - theme-updated
jobs:
    update:
        runs-on: ubuntu-latest
        environment: ABYSSERS_UPDATE_ENV
        steps:
            - name: "[Get Payloads]"
              run: echo ${{ github.event.client_payload }}
            - name: "[Download Repo]"
              uses: actions/checkout@v2
              with:
                  ref: main
                  token: ${{ secrets.MORILENCE_GENERAL_PAT }}
                  submodules: recursive
            - name: "[Update Theme Module]"
              run: git submodule update --init --remote --force
            - name: "[Create Pull Request]"
              uses: peter-evans/create-pull-request@v4
              with:
                  token: ${{ secrets.MORILENCE_GENERAL_PAT }}
                  commit-message: "ci: updated theme to ${{ github.event.client_payload.sha }}"
                  branch: auto/updating/theme
                  delete-branch: true
                  title: "[Auto] theme updated"
                  labels: auto
                  reviewers: |
                      Morilence
                      GarlicGo
                  team-reviewers: |
                      owners
                      developers
                  draft: false
